# Configuration for API keys and settings
TWITTER_BEARER_TOKEN = "YOUR_TWITTER_BEARER_TOKEN"
REDDIT_CLIENT_ID = "YOUR_REDDIT_CLIENT_ID"
REDDIT_CLIENT_SECRET = "YOUR_REDDIT_CLIENT_SECRET"
REDDIT_USER_AGENT = "YOUR_APP_USER_AGENT"
AZURE_ENDPOINT = "YOUR_AZURE_ENDPOINT"
AZURE_KEY = "YOUR_AZURE_KEY"
